"use client";

import { useState } from "react";
import { ProductSEO } from "@/lib/api";
import { slugify } from "@/lib/slug";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import {
  Globe,
  Sparkles,
  Search,
  CheckCircle2,
  AlertCircle,
  ExternalLink,
  Tag,
} from "lucide-react";

interface ProductSEOManagerProps {
  seo: ProductSEO;
  onChange: (seo: ProductSEO) => void;
  productName: string;
  brandName?: string;
  categoryName?: string;
  productDescription?: string;
  disabled?: boolean;
}

export function ProductSEOManager({
  seo,
  onChange,
  productName,
  brandName,
  categoryName,
  productDescription,
  disabled = false,
}: ProductSEOManagerProps) {
  const [keywordDraft, setKeywordDraft] = useState("");

  const update = (updates: Partial<ProductSEO>) => {
    onChange({ ...seo, ...updates });
  };

  const titleLength = (seo.title || "").length;
  const descLength = (seo.description || "").length;

  const autoGenerateSlug = () => {
    const source = productName.trim() || seo.title?.trim() || "";
    if (!source) return;
    const generated = slugify(source);
    update({ slug: generated });
  };

  const autoGenerateDefaults = () => {
    const brand = brandName ? ` | ${brandName}` : "";
    const category = categoryName ? ` – ${categoryName}` : "";
    const proposedTitle = `${productName}${category}${brand} | DietTemple Tunisie`.trim();
    const proposedDesc = productDescription
      ? productDescription.slice(0, 155).trim()
      : `Découvrez ${productName} sur DietTemple Tunisie. Commandez en ligne au meilleur prix avec livraison rapide.`;

    const proposedKeywords = [
      productName.toLowerCase(),
      brandName ? brandName.toLowerCase() : "",
      categoryName ? categoryName.toLowerCase() : "",
      "nutrition sportive",
      "diettemple tunisie",
    ].filter(Boolean);

    update({
      title: proposedTitle,
      description: proposedDesc,
      slug: slugify(productName),
      keywords: Array.from(new Set([...(seo.keywords || []), ...proposedKeywords])),
      index: true,
    });
  };

  const addKeyword = () => {
    const kw = keywordDraft.trim().toLowerCase();
    if (!kw) return;
    const existing = seo.keywords || [];
    if (!existing.includes(kw)) {
      update({ keywords: [...existing, kw] });
    }
    setKeywordDraft("");
  };

  const removeKeyword = (kw: string) => {
    update({ keywords: (seo.keywords || []).filter((k) => k !== kw) });
  };

  const displaySlug = seo.slug || (productName ? slugify(productName) : "produit");
  const previewTitle = seo.title || (productName ? `${productName} | DietTemple Tunisie` : "Titre du produit | DietTemple");
  const previewDesc =
    seo.description ||
    (productDescription
      ? productDescription.slice(0, 155)
      : "Découvrez nos compléments alimentaires, protéines et équipements sportifs sur DietTemple.");

  return (
    <Card className="border-border/80 shadow-sm bg-card/80 backdrop-blur-sm">
      <CardHeader>
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
          <div>
            <CardTitle className="text-base flex items-center gap-2">
              <Globe className="h-4 w-4 text-primary" />
              SEO & Référencement
            </CardTitle>
            <CardDescription className="text-xs mt-1">
              Optimisez la visibilité de votre produit sur Google et les moteurs de recherche.
            </CardDescription>
          </div>

          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={autoGenerateDefaults}
            disabled={disabled || !productName}
            className="gap-1.5 text-xs text-primary border-primary/30 hover:bg-primary/10 h-8 self-start sm:self-auto"
          >
            <Sparkles className="h-3.5 w-3.5" />
            Générer les métadonnées auto
          </Button>
        </div>
      </CardHeader>

      <CardContent className="space-y-5">
        {/* SEO Title */}
        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <Label htmlFor="seo-title">Titre SEO (Meta Title)</Label>
            <span
              className={`text-xs font-mono font-medium ${
                titleLength >= 45 && titleLength <= 65
                  ? "text-emerald-500"
                  : titleLength > 65
                  ? "text-amber-500"
                  : "text-muted-foreground"
              }`}
            >
              {titleLength} / 60 caractères (idéal : 50–60)
            </span>
          </div>
          <Input
            id="seo-title"
            value={seo.title || ""}
            onChange={(e) => update({ title: e.target.value })}
            placeholder="Ex: Optimum Nutrition Gold Standard 100% Whey | DietTemple"
            disabled={disabled}
          />
        </div>

        {/* Meta Description */}
        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <Label htmlFor="seo-description">Meta Description</Label>
            <span
              className={`text-xs font-mono font-medium ${
                descLength >= 130 && descLength <= 165
                  ? "text-emerald-500"
                  : descLength > 165
                  ? "text-amber-500"
                  : "text-muted-foreground"
              }`}
            >
              {descLength} / 160 caractères (idéal : 140–160)
            </span>
          </div>
          <Textarea
            id="seo-description"
            value={seo.description || ""}
            onChange={(e) => update({ description: e.target.value })}
            placeholder="Ex: Découvrez la Whey Gold Standard d'Optimum Nutrition en Tunisie. 24g de protéines de haute qualité par dose pour accompagner vos objectifs musculaires."
            rows={3}
            disabled={disabled}
          />
        </div>

        {/* Slug and Canonical */}
        <div className="grid gap-4 sm:grid-cols-2">
          {/* URL Slug */}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <Label htmlFor="seo-slug">Slug d'URL *</Label>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={autoGenerateSlug}
                disabled={disabled || !productName}
                className="h-6 px-1.5 text-xs text-primary gap-1"
              >
                <Sparkles className="h-3 w-3" />
                Générer
              </Button>
            </div>
            <div className="relative flex items-center">
              <span className="absolute left-3 text-xs text-muted-foreground select-none">/boutique/</span>
              <Input
                id="seo-slug"
                value={seo.slug || ""}
                onChange={(e) => update({ slug: slugify(e.target.value) })}
                placeholder="gold-standard-100-whey"
                className="pl-24 font-mono text-xs"
                disabled={disabled}
              />
            </div>
          </div>

          {/* Canonical URL */}
          <div className="space-y-1.5">
            <Label htmlFor="seo-canonical">URL Canonique (optionnel)</Label>
            <Input
              id="seo-canonical"
              value={seo.canonical || ""}
              onChange={(e) => update({ canonical: e.target.value.trim() })}
              placeholder="https://diettemple.tn/boutique/..."
              className="text-xs"
              disabled={disabled}
            />
          </div>
        </div>

        {/* Keywords */}
        <div className="space-y-2">
          <Label htmlFor="seo-keywords">Mots-clés SEO (Keywords)</Label>
          <div className="flex gap-2">
            <Input
              id="seo-keywords"
              value={keywordDraft}
              onChange={(e) => setKeywordDraft(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === ",") {
                  e.preventDefault();
                  addKeyword();
                }
              }}
              placeholder="Ajouter un mot-clé (Appuyez sur Entrée)…"
              className="text-xs"
              disabled={disabled}
            />
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={addKeyword}
              disabled={disabled || !keywordDraft.trim()}
            >
              Ajouter
            </Button>
          </div>

          {Array.isArray(seo.keywords) && seo.keywords.length > 0 && (
            <div className="flex flex-wrap gap-1.5 pt-1">
              {seo.keywords.map((kw) => (
                <span
                  key={kw}
                  className="inline-flex items-center gap-1 rounded-md bg-secondary/80 text-secondary-foreground px-2.5 py-0.5 text-xs font-medium"
                >
                  <Tag className="h-3 w-3 opacity-60" />
                  {kw}
                  <button
                    type="button"
                    onClick={() => removeKeyword(kw)}
                    className="hover:text-destructive ml-0.5 font-bold"
                    aria-label={`Supprimer ${kw}`}
                  >
                    ×
                  </button>
                </span>
              ))}
            </div>
          )}
        </div>

        {/* Indexation Toggle */}
        <div className="pt-2 border-t border-border/50">
          <label className="flex items-center gap-2 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={seo.index !== false}
              onChange={(e) => update({ index: e.target.checked })}
              disabled={disabled}
              className="h-4 w-4 rounded border-border text-primary focus:ring-primary/20 cursor-pointer"
            />
            <span className="text-sm font-medium text-foreground">
              Autoriser les moteurs de recherche à indexer ce produit (index, follow)
            </span>
          </label>
        </div>

        {/* Google SERP Preview */}
        <div className="pt-4 border-t border-border/50 space-y-2">
          <div className="flex items-center gap-1.5 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
            <Search className="h-3.5 w-3.5 text-primary" />
            Aperçu dans les résultats Google
          </div>

          <div className="rounded-xl border border-border/80 bg-background/90 p-4 space-y-1 shadow-sm font-sans">
            {/* SERP Breadcrumb */}
            <div className="flex items-center gap-1.5 text-[11px] text-muted-foreground">
              <div className="h-4 w-4 rounded-full bg-primary/20 text-primary flex items-center justify-center text-[8px] font-bold">
                DT
              </div>
              <span className="text-foreground font-medium">diettemple.tn</span>
              <span>›</span>
              <span className="truncate">boutique › {displaySlug}</span>
            </div>

            {/* SERP Title */}
            <h4 className="text-base font-medium text-blue-600 dark:text-blue-400 hover:underline cursor-pointer line-clamp-1">
              {previewTitle}
            </h4>

            {/* SERP Description */}
            <p className="text-xs text-muted-foreground line-clamp-2 leading-relaxed">
              {previewDesc}
            </p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
